healthy_app/healthy_app/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/nutrition/', permanent=True)),
    path('exercises/', include('exercise.urls')),
    path('nutrition/', include('nutrition.urls')),
    path('', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

healthy_app/nutrition/urls.py
from . import views
from django.contrib import admin
from django.urls import path
from . import views as main_views

urlpatterns = [
    # path('get_nutrition/', views.NutritionView.as_view(), name='get_nutrition'),
    path('get_nutrition/', views.NutritionView.as_view(), name='get_nutrition'),
    path('', main_views.MainView.as_view(), name='base'),
    # path('show_nutrition/', views.ConvertingNutrition.as_view(), name='nutrition'),
]

healthy_app/users/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from .views import ProfileView, ShowPlans, ShowExercises, MealPlanDetailView
from . import ajax_datatable_views
app_name = 'users'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('ajax/register/', views.AjaxRegisterView.as_view(), name='ajax_register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('show-plans/', ShowPlans.as_view(), name='show-plans'),
    path('show-exercises/', ShowExercises.as_view(), name='show-exercises'),
    path('ajax/datatable/nutrition/', ajax_datatable_views.NutritionAjaxDatatableView.as_view(), name="ajax_datatable_nutrition"),
    path('ajax/datatable/workouts/', ajax_datatable_views.WorkoutsAjaxDatatableView.as_view(), name="ajax_datatable_workouts"),
    path('meal-plan/<int:pk>/', MealPlanDetailView.as_view(), name="meal_plan_detail"),
]

healthy_app/nutrition/models.py
from datetime import datetime
from django.db import models
from users.models import Profile
from django.contrib.auth.models import User

class MealPlan(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='użytkownik healthy_app')
    datetime = models.DateTimeField(default=datetime.now)
    meal_json = models.JSONField(verbose_name='meal_plan_json')
    general_health = models.CharField(max_length=100, null=True)
    general_min_kcal = models.IntegerField(max_length=100, null=True)
    general_max_kcal = models.IntegerField(max_length=100, null=True)
    photo = models.ImageField(max_length=2000, null=True)
    page_title = models.CharField(max_length=1000, default='dish')

healthy_app/nutrition/forms.py
from django import forms


class NutritionGeneralForm(forms.Form):
    # size = forms.IntegerField(label='size', required=True, min_value=1, max_value=7)
    health_choices = [
        ('egg-free', 'bez jaj'), ('fish-free', 'bez ryb'), ('tree-nut-free', 'bez orzechów'),
        ('low-sugar', 'dieta niskocukrowa'), ('vegan', 'dieta wegańska'), ('vegetarian', 'dieta wegetariańska')
    ]
    general_health = forms.MultipleChoiceField(label='general_health', choices=health_choices, widget=forms.CheckboxSelectMultiple)
    general_min_kcal = forms.IntegerField(label='general_min_kcal', required=True)
    general_max_kcal = forms.IntegerField(label='general_max_kcal', required=True)
    email = forms.EmailField()

healthy_app/nutrition/views.py
import urllib
from django.shortcuts import render
import requests
import json
from django.conf import settings
from django.http import HttpResponse
from django.views.generic import TemplateView
from .forms import NutritionGeneralForm
from exercise.forms import ExerciseForm
from users.forms import UserRegisterForm
from bs4 import BeautifulSoup
from .models import MealPlan
from django.core.mail import send_mail
from healthy_app.settings import EMAIL_HOST_USER

class MainView(TemplateView):
    template_name = 'nutrition/main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['exercise_form'] = ExerciseForm()
        context['nutrition_form'] = NutritionGeneralForm()
        context['register_form'] = UserRegisterForm()
        return context


class NutritionView(TemplateView):
    template_name = 'nutrition/show_nutrition.html'


    def get(self, request):
        form = NutritionGeneralForm(request.GET)
        return render(request, 'nutrition/nutrition.html', {'form': form})

    def post(self, request):
        form = NutritionGeneralForm(request.POST)
        if form.is_valid():
            size = 1
            general_health = form.cleaned_data['general_health']
            general_min_kcal = form.cleaned_data['general_min_kcal']
            general_max_kcal = form.cleaned_data['general_max_kcal']
            email = form.cleaned_data['email']
            print(general_max_kcal)
            diet_plan_request = {"size": size, "plan": {"accept": {"all": [{"health": general_health}]}, "fit": {"ENERC_KCAL": {"min": general_min_kcal, "max": general_max_kcal}}, "sections": {"Breakfast": {"accept": {"all": [{"meal": ["breakfast"]}]}}, "Lunch": {"accept": {"all": [{"meal": ["lunch/dinner"]}]}}, "Dinner": {"accept": {"all": [{"meal": ["lunch/dinner"]}]}}}}}
            nutrition_api_key = settings.NUTRITION_API_KEY
            nutrition_id = settings.NUTRITION_ID
            api_url = f'https://api.edamam.com/api/meal-planner/v1/{nutrition_id}/select'
            headers = {
                'Content-type': 'application/json',
                'Accept': 'application/json',
                'Authorization': 'Basic YTdkZWI3MDg6MmY4N2IxOTc4YTExMmU2YThhYjc1M2Y3YjI4ZmU2YWM=',
                'Edamam-Account-User': '1',
            }
            response = requests.post(api_url, data=json.dumps(diet_plan_request), headers=headers)
            response = response.json()
            data = response
            list_of_links = []
            for i in range(size):
                list_of_links.append(data['selection'][i]['sections']['Breakfast']['assigned'])
                list_of_links.append(data['selection'][i]['sections']['Dinner']['assigned'])
                list_of_links.append(data['selection'][i]['sections']['Lunch']['assigned'])

            headers2 = {
                'accept': 'application/json',
                'Accept-Language': 'en',
                'Edamam-Account-User': '1',
            }
            recipes = []
            for link in list_of_links:
                nutrition_api_key = '2f87b1978a112e6a8ab753f7b28fe6ac'
                nutrition_id = 'a7deb708'
                api_endpoint = 'https://api.edamam.com/api/recipes/v2/by-uri?type=public&'
                request_body = urllib.parse.quote_plus(f'uri={link}&app_id={nutrition_id}&app_key={nutrition_api_key}&field=url&field=image&field=ingredients&field=totalNutrients', safe='=&')
                api_url = f'{api_endpoint}{request_body}'
                recipe = requests.get(api_url, headers=headers2)
                recipes.append(recipe.json())

            sorted_data = []

            for element in recipes:
                list_of_ingredients = []
                for value in element['hits'][0]['recipe']['ingredients']:
                    list_of_ingredients.append(value['text'])

                def get_page_title(url):
                    try:
                        response = requests.get(url)
                        response.raise_for_status()
                        soup = BeautifulSoup(response.text, 'html.parser')
                        page_title = soup.title.string

                        return page_title
                    except Exception as e:

                        return 'tytul'

                page_title = get_page_title(element['hits'][0]['recipe']['url'])

                sorted_data.append(
                        {'image': element['hits'][0]['recipe']['image'], 'url': element['hits'][0]['recipe']['url'],
                         'ingredients': list_of_ingredients, 'page_title': page_title})
                photo = element['hits'][0]['recipe']['image']


            send_mail(
                "Welcome to Healthy_App",
                "You just got your diet meal plan on healthy_app, congrats!",
                EMAIL_HOST_USER,
                [email],
                fail_silently=False,
            )

            MealPlan.objects.create(user=self.request.user, meal_json=recipes, general_health=general_health, general_min_kcal=general_min_kcal, general_max_kcal=general_max_kcal, photo=photo, page_title=page_title)

            print(sorted_data)
            first_meal = sorted_data[0]
            second_meal = sorted_data[1]
            first_meal = sorted_data[2]

            return render(request, self.template_name, {'sorted_data': sorted_data})

        else:
            print('Formularz nie działa')
            return HttpResponse('Błąd formularza')

healthy_app/nutrition/templates/nutrition/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'nutrition/base.css' %}" />
    <style>
        .custom-container {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        .c-container {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            color: #FFFFFF;
        }

        body {
    background-color: #000000;
}
        .card{
            background-color: #000000;}
        .card-body{
            background-color: #000000;}
        .card-title{
            background-color: #000000;}
        .card-text{
            background-color: #000000;}
        .btn{
            background-color: #000000;}
            color: #FFFFFF;

        .btn:hover{
            background-color: #000000;
            color:#F4A460;
        }

        .lista{
            color:#FFFFFF;
        }

    </style>
    <script
  src="https://code.jquery.com/jquery-3.7.1.min.js"
  integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'users/register.js' %}"></script>
     <script src="{% static 'ajax_datatable/js/utils.js' %}"></script>
    <script src="https://cdn.datatables.net/v/bs5/dt-2.0.2/date-1.5.2/datatables.min.js"></script>
    {% block extrajs %}
    {% endblock %}
    <title>Healthy app</title>

</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/nutrition">Healthy_app</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav ms-auto">

                        {% if not user.is_authenticated %}
                            <a href="" data-bs-toggle="modal" data-bs-target="#ModelLogin">Log in</a>
                            <a href="" data-bs-toggle="modal" data-bs-target="#ModelRegister">Register</a>
                        {% endif %}

                        {% if user.is_authenticated %}
                        <p>{{ user.username }}</p>
                            <a class="nav-item nav-link" href="/profile">Profile</a>
                            <form action="{% url 'users:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit">Log Out</button>
                            </form>
                        {% endif %}
                    </div>

                </div>
            </div>
        </nav>
    </header>

<main role="main" class="container">

    {% block space %}{% endblock %}



<div class="modal" tabindex="-1" role="dialog" id="ModelLogin">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Zaloguj się</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form method="post" id="login-form-id" action="{% url 'users:login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Nazwa użytkownika:</label>
                <input type="text" name="username" class="form-control" required id="id_username">
            </div>
            <div class="form-group">
                <label for="id_password">Hasło:</label>
                <input type="password" name="password" class="form-control" required id="id_password">
            </div>
            <button type="submit" class="btn btn-primary">Zaloguj</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">zamknij</button>
      </div>
    </div>
  </div>
</div>

  <div class="modal" tabindex="-1" id="ModelRegister">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Zarejestruj się</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
            <div class="modal-body">
                <form id="register-form-id" method="post" action="{% url 'users:ajax_register' %}">
                    {% csrf_token %}
                    {{ register_form }}
                    <button class="btn btn-primary" type="submit" form="register-form-id">register</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">zamknij</button>
                </form>
            </div>
    </div>
</div>
    </div>

    <div class="modal" id="successModal" tabindex="-1" aria-labelledby="succesModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="succesModal">Gratulations!</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>You are registered now!</p>
                </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary close" data-bs-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>
    </div>


</main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->


</body>
</html>

healthy_app/nutrition/templates/nutrition/main.html
{% extends 'nutrition/base.html' %}
{% load static %}
{% block space %}

     <div class="row">
         <div class="col-md-8">
             {% if messages %}
                {% for message in messages %}
                    <div class ="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
             {% endif %}
             {% block content %}{% endblock %}
         </div>
     </div>
<div class="custom-container">
    <div class="row text-center " style="width: 80rem">

  <div class="card col-6 mb-10">
    <img class="card1-img-top" src="{% static 'images/man.jpg' %}">
    <div class="card-body">
      <h5 class="card-title text-light">Dobierz Trening</h5>
      <p class="card-text text-light">Pobierz indywidualny plan treningowy z opisami ćwiczeń:</p>
      <a href="" data-bs-toggle="modal" data-bs-target="#ModelExercise">Dobierz Plan</a>
    </div>
  </div>

  <div class="card col-6 mb-10">
    <img class="card2-img-top" src="{% static 'images/steak.jpg' %}" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title text-light">Dobierz Plan Żywieniowy</h5>
      <p class="card-text text-light">Na podstawie podanych informacji dobierzesz indywidualną dietę na nawet 7 dni:</p>
      <a href="" data-bs-toggle="modal" data-bs-target="#ModelNutrition">Dobierz dietę</a>
    </div>
  </div>



</div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="ModelExercise">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Wypełnij formularz</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" id="exercise-form-id" action="{% url 'exercise' %}">
            {% csrf_token %}
            {{ exercise_form }}
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" type="submit" form="exercise-form-id">wyślij</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">zamknij</button>
      </div>
    </div>
  </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="ModelNutrition">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Wypełnij formularz</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form method="post" id="nutrition-form-id" action="{% url 'get_nutrition' %}">
            {% csrf_token %}
            {{ nutrition_form }}
          </form>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" type="submit" form="nutrition-form-id">wyślij</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">zamknij</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

healthy_app/nutrition/templates/nutrition/nutrition.html
{% extends "nutrition/base.html" %}
{% block title %} znajdź plan żywienia {% endblock %}
{% block space %}

<div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">

                {{ form }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Show meal plan</button>
            </div>
        </form>
</div>

{% endblock %}

healthy_app/nutrition/templates/nutrition/show_nutrition.html
{% extends 'nutrition/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'nutrition/show_nutrition.css' %}">
{% endblock %}

{% block space %}

<div class="c-container">
    <div class="row justify-content-center col-md-12 align-items-center">

        {% for recipe in sorted_data %}
            <div class="card col-md-4">
                <img class="card-img-top" src= {{ recipe.image }} alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{ recipe.page_title }}</h5>
                    <h2>składniki:</h2>
                    {% for ingredient in recipe.ingredients %}
                    <ul>
                        <li>{{ ingredient }}</li>
                    </ul>
                    {% endfor %}
                    <a href= {{ recipe.url }}>link do pełnego przepisu</a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}