healthy_app/healthy_app/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/nutrition/', permanent=True)),
    path('exercises/', include('exercise.urls')),
    path('nutrition/', include('nutrition.urls')),
    path('', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

healthy_app/users/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from .views import ProfileView, ShowPlans, ShowExercises, MealPlanDetailView
from . import ajax_datatable_views
app_name = 'users'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('ajax/register/', views.AjaxRegisterView.as_view(), name='ajax_register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('show-plans/', ShowPlans.as_view(), name='show-plans'),
    path('show-exercises/', ShowExercises.as_view(), name='show-exercises'),
    path('ajax/datatable/nutrition/', ajax_datatable_views.NutritionAjaxDatatableView.as_view(), name="ajax_datatable_nutrition"),
    path('ajax/datatable/workouts/', ajax_datatable_views.WorkoutsAjaxDatatableView.as_view(), name="ajax_datatable_workouts"),
    path('meal-plan/<int:pk>/', MealPlanDetailView.as_view(), name="meal_plan_detail"),
]

healthy_app/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.ppg', upload_to='profile_pics')


    def __str__(self):
        return f'Profile of {self.user.get_full_name()}'

healthy_app/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.forms import User
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

healthy_app/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth import authenticate, login
from django.views import View, generic
from django.http import HttpResponse
from django.views.generic import ListView
from .forms import UserRegisterForm, ProfileUpdateForm, UserUpdateForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.decorators import login_required
from nutrition.models import MealPlan
from exercise.models import Exercises
from bs4 import BeautifulSoup
import requests
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView


class AjaxRegisterView(View):

    # def get_context_data(self, **kwargs):
    #     context['register_form'] = UserRegisterForm()
    #     return context

    def get(self, request):
        form = UserRegisterForm()
        return render(request, 'register.html', {'form': form})

    def post(self, request):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'errors': form.errors})


class LoginView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'login.html')

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('base')  # Przekierowanie do strony po zalogowaniu
        else:
            return HttpResponse('Nieprawidłowe dane logowania')


class ProfileView(LoginRequiredMixin, View):
    template_name = 'users/profile.html'
    succes_url = reverse_lazy('users:profile')

    def get(self, request, *args, **kwargs):
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
        return render(request, self.template_name, {'user_form': user_form, 'profile_form': profile_form})

    def post(self, request, *args, **kwargs):
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Your profile has been updated")
            return redirect(self.success_url)

        return render(request, self.template_name, {'user_form': user_form, 'profile_form': profile_form})


class ShowPlans(View):
    def get(self, request, *args, **kwargs):
        mealplans = MealPlan.objects.filter(user=request.user)
        recipes = []

        for element in mealplans:
            recipes.append(element.meal_json[0])

        print(recipes )

        sorted_data = []

        for e in recipes:
            list_of_ingredients = []
            for value in e['hits'][0]['recipe']['ingredients']:
                list_of_ingredients.append(value['text'])

            def get_page_title(url):
                try:
                    response = requests.get(url)
                    response.raise_for_status()
                    soup = BeautifulSoup(response.text, 'html.parser')
                    page_title = soup.title.string

                    return page_title
                except Exception as e:

                    return 'tytul'

            page_title = get_page_title(e['hits'][0]['recipe']['url'])

            sorted_data.append(
                {'image': e['hits'][0]['recipe']['image'], 'url': e['hits'][0]['recipe']['url'],
                 'ingredients': list_of_ingredients, 'page_title': page_title})
            photo = e['hits'][0]['recipe']['image']

        print(sorted_data)

        return render(request, 'users/show_plans.html', {'sorted_data': sorted_data})


class ShowExercises(ListView):
    model = Exercises
    template_name = 'users/show_workouts.html'
    def get_queryset(self):
        return Exercises.objects.filter(user=self.request.user)


class MealPlanDetailView(DetailView):
    model = MealPlan
    template_name = 'meal_plan_detail.html'

healthy_app/users/templates/users/meal_plan_detail.html
{% load static %}
{% block space %}

<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
</div>

<div class="c-container">
    <div class="row justify-content-center col-md-12 align-items-center">
        {{ meal_plan }}

    </div>
</div>

{% endblock %}

healthy_app/users/templates/users/plan_table.html
{% load static %}
{% block space %}

<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
</div>

<div class="c-container">
    <div class="row justify-content-center col-md-12 align-items-center">
        {{ meal_plan }}

    </div>
</div>

{% endblock %}

healthy_app/users/templates/users/profile.html
{% extends 'nutrition/base.html' %}
{% load static %}
{% block extrastyle %}

    <link href="{% static 'ajax_datatable/css/style.css' %}" rel="stylesheet" />

{% endblock extrastyle %}

{% block space %}

<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
            <a class="nav-item nav-link" href="/show-plans">Your diet plans</a>
            <a class="nav-item nav-link" href="/show-exercises">Your workouts</a>
        </div>
    </div>
</div>

<div class="bg-white">
    <table id="datatable_nutrition">
</table>
</div>

<div class="bg-white">
    <table id="datatable_workouts">
</table>
</div>


 <div class="modal" tabindex="-1" id="ModelRegister">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Zarejestruj się</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
            <div class="modal-body">
                <form id="register-form-id" method="post" action="{% url 'users:ajax_register' %}">
                    {% csrf_token %}
                    {{ register_form }}
                    <button class="btn btn-primary" type="submit" form="register-form-id">register</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">zamknij</button>
                </form>
            </div>
    </div>
</div>
    </div>
{% endblock %}


{% block extrajs %}

    <script language="javascript">

        $(document).ready(function() {
            AjaxDatatableViewUtils.initialize_table(
                $('#datatable_nutrition'),
                "{% url 'users:ajax_datatable_nutrition' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: false,
                    full_row_select: true,
                    scrollX: false
                }, {
                    // extra_data
                    // ...
                },
            );

             AjaxDatatableViewUtils.initialize_table(
                $('#datatable_workouts'),
                "{% url 'users:ajax_datatable_workouts' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: false,
                    full_row_select: true,
                    scrollX: false
                }, {
                    // extra_data
                    // ...
                },
            );
        });

    </script>

{% endblock %}

healthy_app/users/templates/users/register.html
{% extends 'exercise/base.html' %}
{% block content %}
    <div class="content-section">
        <form method ='POST'>
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Dołącz!</legend>
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Zarejestruj się!</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Masz już konto? <a class="ml-2" href="#">Zaloguj się!</a>
            </small>
        </div>
    </div>
{% endblock %}

healthy_app/users/templates/users/show_plans.html
{% load static %}
{% block space %}

<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
</div>

<div class="c-container">
    <div class="row justify-content-center col-md-12 align-items-center">

        {% for recipe in sorted_data %}
            <div class="card col-md-4">
                <img class="card-img-top" src= {{ recipe.image }} alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{ recipe.page_title }}</h5>
                    <h2>składniki:</h2>
                    {% for ingredient in recipe.ingredients %}
                    <ul>
                        <li>{{ ingredient }}</li>
                    </ul>
                    {% endfor %}
                    <a href= {{ recipe.url }}>link do pełnego przepisu</a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

healthy_app/users/templates/users/show_workouts.html
{% extends 'nutrition/base.html' %}
{% block title %} twoje ćwiczenia {% endblock %}
{% block space %}

<h2></h2>
<div class="exercises-list">
    Liczba obiektów: {{ object_list.count }}
<ul>


    {% for exercise in object_list %}
        <li>{{ exercise }}</li>
    {% endfor %}
</ul>
</div>

{% endblock %}